version: "3.7"

services:

  db:
    image: postgres:11.2-alpine
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_DB=mlflowdb
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - mlflow-db:/var/lib/postgresql/data/pgdata

  mlflow-server:
    image: gregsi/docker-mlflow-server:1.20.0
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=db
      - DB_NAME=mlflowdb
      - DB_USER=${POSTGRES_USER}
      - DB_PASSWD=${POSTGRES_PASSWORD}
    depends_on:
      - db

volumes:
  mlflow-db:
